version: "3"
services:
    react-app:
        container_name: overwatch
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8079:80
        env_file:
            - .env
        expose:
            - "8079"
        volumes:
            - ./src:/app/src
        restart: unless-stopped
