import { useEffect, useState } from "react";
import randomColor from "randomcolor";
import { Dimensions } from "react-native";

export const heroMap = {
	"ana/profile_pic.png": require("../assets/overwatch/heroes/ana/profile_pic.png"),
	"ana/biotic_rifle.png": require("../assets/overwatch/heroes/ana/biotic_rifle.png"),
	"ana/sleep_dart.png": require("../assets/overwatch/heroes/ana/sleep_dart.png"),
	"ana/biotic_grenade.png": require("../assets/overwatch/heroes/ana/biotic_grenade.png"),
	"ana/nano_boost.png": require("../assets/overwatch/heroes/ana/nano_boost.png"),
	"ashe/profile_pic.png": require("../assets/overwatch/heroes/ashe/profile_pic.png"),
	"ashe/the_viper.png": require("../assets/overwatch/heroes/ashe/the_viper.png"),
	"ashe/dynamite.png": require("../assets/overwatch/heroes/ashe/dynamite.png"),
	"ashe/coach_gun.png": require("../assets/overwatch/heroes/ashe/coach_gun.png"),
	"ashe/b_o_b_.png": require("../assets/overwatch/heroes/ashe/b_o_b_.png"),
	"baptiste/profile_pic.png": require("../assets/overwatch/heroes/baptiste/profile_pic.png"),
	"baptiste/biotic_launcher.png": require("../assets/overwatch/heroes/baptiste/biotic_launcher.png"),
	"baptiste/regenerative_burst.png": require("../assets/overwatch/heroes/baptiste/regenerative_burst.png"),
	"baptiste/immortality_field.png": require("../assets/overwatch/heroes/baptiste/immortality_field.png"),
	"baptiste/amplification_matrix.png": require("../assets/overwatch/heroes/baptiste/amplification_matrix.png"),
	"baptiste/exo_boots.png": require("../assets/overwatch/heroes/baptiste/exo_boots.png"),
	"bastion/profile_pic.png": require("../assets/overwatch/heroes/bastion/profile_pic.png"),
	"bastion/configuration__recon.png": require("../assets/overwatch/heroes/bastion/configuration__recon.png"),
	"bastion/configuration__assault.png": require("../assets/overwatch/heroes/bastion/configuration__assault.png"),
	"bastion/reconfigure.png": require("../assets/overwatch/heroes/bastion/reconfigure.png"),
	"bastion/a_36_tactical_grenade.png": require("../assets/overwatch/heroes/bastion/a_36_tactical_grenade.png"),
	"bastion/configuration__artillery.png": require("../assets/overwatch/heroes/bastion/configuration__artillery.png"),
	"bastion/ironclad.png": require("../assets/overwatch/heroes/bastion/ironclad.png"),
	"cassidy/profile_pic.png": require("../assets/overwatch/heroes/cassidy/profile_pic.png"),
	"cassidy/peacekeeper.png": require("../assets/overwatch/heroes/cassidy/peacekeeper.png"),
	"cassidy/combat_roll.png": require("../assets/overwatch/heroes/cassidy/combat_roll.png"),
	"cassidy/magnetic_grenade.png": require("../assets/overwatch/heroes/cassidy/magnetic_grenade.png"),
	"cassidy/deadeye.png": require("../assets/overwatch/heroes/cassidy/deadeye.png"),
	"d_va/profile_pic.png": require("../assets/overwatch/heroes/d_va/profile_pic.png"),
	"d_va/fusion_cannons.png": require("../assets/overwatch/heroes/d_va/fusion_cannons.png"),
	"d_va/boosters.png": require("../assets/overwatch/heroes/d_va/boosters.png"),
	"d_va/defense_matrix.png": require("../assets/overwatch/heroes/d_va/defense_matrix.png"),
	"d_va/micro_missiles.png": require("../assets/overwatch/heroes/d_va/micro_missiles.png"),
	"d_va/self_destruct.png": require("../assets/overwatch/heroes/d_va/self_destruct.png"),
	"d_va/eject_.png": require("../assets/overwatch/heroes/d_va/eject_.png"),
	"d_va/light_gun.png": require("../assets/overwatch/heroes/d_va/light_gun.png"),
	"d_va/call_mech.png": require("../assets/overwatch/heroes/d_va/call_mech.png"),
	"doomfist/profile_pic.png": require("../assets/overwatch/heroes/doomfist/profile_pic.png"),
	"doomfist/hand_cannon.png": require("../assets/overwatch/heroes/doomfist/hand_cannon.png"),
	"doomfist/rocket_punch.png": require("../assets/overwatch/heroes/doomfist/rocket_punch.png"),
	"doomfist/seismic_slam.png": require("../assets/overwatch/heroes/doomfist/seismic_slam.png"),
	"doomfist/power_block.png": require("../assets/overwatch/heroes/doomfist/power_block.png"),
	"doomfist/meteor_strike.png": require("../assets/overwatch/heroes/doomfist/meteor_strike.png"),
	"doomfist/the_best_defense___.png": require("../assets/overwatch/heroes/doomfist/the_best_defense___.png"),
	"echo/profile_pic.png": require("../assets/overwatch/heroes/echo/profile_pic.png"),
	"echo/tri_shot.png": require("../assets/overwatch/heroes/echo/tri_shot.png"),
	"echo/sticky_bombs.png": require("../assets/overwatch/heroes/echo/sticky_bombs.png"),
	"echo/flight.png": require("../assets/overwatch/heroes/echo/flight.png"),
	"echo/focusing_beam.png": require("../assets/overwatch/heroes/echo/focusing_beam.png"),
	"echo/duplicate.png": require("../assets/overwatch/heroes/echo/duplicate.png"),
	"echo/glide.png": require("../assets/overwatch/heroes/echo/glide.png"),
	"genji/profile_pic.png": require("../assets/overwatch/heroes/genji/profile_pic.png"),
	"genji/shuriken.png": require("../assets/overwatch/heroes/genji/shuriken.png"),
	"genji/swift_strike.png": require("../assets/overwatch/heroes/genji/swift_strike.png"),
	"genji/deflect.png": require("../assets/overwatch/heroes/genji/deflect.png"),
	"genji/dragonblade.png": require("../assets/overwatch/heroes/genji/dragonblade.png"),
	"genji/cyber_agility.png": require("../assets/overwatch/heroes/genji/cyber_agility.png"),
	"hanzo/profile_pic.png": require("../assets/overwatch/heroes/hanzo/profile_pic.png"),
	"hanzo/storm_bow.png": require("../assets/overwatch/heroes/hanzo/storm_bow.png"),
	"hanzo/sonic_arrow.png": require("../assets/overwatch/heroes/hanzo/sonic_arrow.png"),
	"hanzo/storm_arrows.png": require("../assets/overwatch/heroes/hanzo/storm_arrows.png"),
	"hanzo/lunge.png": require("../assets/overwatch/heroes/hanzo/lunge.png"),
	"hanzo/dragonstrike.png": require("../assets/overwatch/heroes/hanzo/dragonstrike.png"),
	"hanzo/wall_climb.png": require("../assets/overwatch/heroes/hanzo/wall_climb.png"),
	"junker_queen/profile_pic.png": require("../assets/overwatch/heroes/junker_queen/profile_pic.png"),
	"junker_queen/scattergun.png": require("../assets/overwatch/heroes/junker_queen/scattergun.png"),
	"junker_queen/jagged_blade.png": require("../assets/overwatch/heroes/junker_queen/jagged_blade.png"),
	"junker_queen/commanding_shout.png": require("../assets/overwatch/heroes/junker_queen/commanding_shout.png"),
	"junker_queen/carnage.png": require("../assets/overwatch/heroes/junker_queen/carnage.png"),
	"junker_queen/rampage.png": require("../assets/overwatch/heroes/junker_queen/rampage.png"),
	"junker_queen/adrenaline_rush.png": require("../assets/overwatch/heroes/junker_queen/adrenaline_rush.png"),
	"junkrat/profile_pic.png": require("../assets/overwatch/heroes/junkrat/profile_pic.png"),
	"junkrat/frag_launcher.png": require("../assets/overwatch/heroes/junkrat/frag_launcher.png"),
	"junkrat/concussion_mine.png": require("../assets/overwatch/heroes/junkrat/concussion_mine.png"),
	"junkrat/steel_trap.png": require("../assets/overwatch/heroes/junkrat/steel_trap.png"),
	"junkrat/rip_tire.png": require("../assets/overwatch/heroes/junkrat/rip_tire.png"),
	"junkrat/total_mayhem.png": require("../assets/overwatch/heroes/junkrat/total_mayhem.png"),
	"kiriko/profile_pic.png": require("../assets/overwatch/heroes/kiriko/profile_pic.png"),
	"kiriko/healing_ofuda.png": require("../assets/overwatch/heroes/kiriko/healing_ofuda.png"),
	"kiriko/kunai.png": require("../assets/overwatch/heroes/kiriko/kunai.png"),
	"kiriko/swift_step.png": require("../assets/overwatch/heroes/kiriko/swift_step.png"),
	"kiriko/protection_suzu.png": require("../assets/overwatch/heroes/kiriko/protection_suzu.png"),
	"kiriko/kitsune_rush.png": require("../assets/overwatch/heroes/kiriko/kitsune_rush.png"),
	"kiriko/wall_climb.png": require("../assets/overwatch/heroes/kiriko/wall_climb.png"),
	"lucio/profile_pic.png": require("../assets/overwatch/heroes/lucio/profile_pic.png"),
	"lucio/sonic_amplifier.png": require("../assets/overwatch/heroes/lucio/sonic_amplifier.png"),
	"lucio/soundwave.png": require("../assets/overwatch/heroes/lucio/soundwave.png"),
	"lucio/crossfade.png": require("../assets/overwatch/heroes/lucio/crossfade.png"),
	"lucio/amp_it_up.png": require("../assets/overwatch/heroes/lucio/amp_it_up.png"),
	"lucio/sound_barrier.png": require("../assets/overwatch/heroes/lucio/sound_barrier.png"),
	"lucio/wall_ride.png": require("../assets/overwatch/heroes/lucio/wall_ride.png"),
	"mei/profile_pic.png": require("../assets/overwatch/heroes/mei/profile_pic.png"),
	"mei/endothermic_blaster.png": require("../assets/overwatch/heroes/mei/endothermic_blaster.png"),
	"mei/cryo_freeze.png": require("../assets/overwatch/heroes/mei/cryo_freeze.png"),
	"mei/ice_wall.png": require("../assets/overwatch/heroes/mei/ice_wall.png"),
	"mei/blizzard.png": require("../assets/overwatch/heroes/mei/blizzard.png"),
	"mercy/profile_pic.png": require("../assets/overwatch/heroes/mercy/profile_pic.png"),
	"mercy/caduceus_staff.png": require("../assets/overwatch/heroes/mercy/caduceus_staff.png"),
	"mercy/caduceus_blaster.png": require("../assets/overwatch/heroes/mercy/caduceus_blaster.png"),
	"mercy/guardian_angel.png": require("../assets/overwatch/heroes/mercy/guardian_angel.png"),
	"mercy/resurrect.png": require("../assets/overwatch/heroes/mercy/resurrect.png"),
	"mercy/valkyrie.png": require("../assets/overwatch/heroes/mercy/valkyrie.png"),
	"mercy/angelic_descent.png": require("../assets/overwatch/heroes/mercy/angelic_descent.png"),
	"moira/profile_pic.png": require("../assets/overwatch/heroes/moira/profile_pic.png"),
	"moira/biotic_grasp.png": require("../assets/overwatch/heroes/moira/biotic_grasp.png"),
	"moira/biotic_orb.png": require("../assets/overwatch/heroes/moira/biotic_orb.png"),
	"moira/fade.png": require("../assets/overwatch/heroes/moira/fade.png"),
	"moira/coalescence.png": require("../assets/overwatch/heroes/moira/coalescence.png"),
	"orisa/profile_pic.png": require("../assets/overwatch/heroes/orisa/profile_pic.png"),
	"orisa/augmented_fusion_driver.png": require("../assets/overwatch/heroes/orisa/augmented_fusion_driver.png"),
	"orisa/energy_javelin.png": require("../assets/overwatch/heroes/orisa/energy_javelin.png"),
	"orisa/fortify.png": require("../assets/overwatch/heroes/orisa/fortify.png"),
	"orisa/javelin_spin.png": require("../assets/overwatch/heroes/orisa/javelin_spin.png"),
	"orisa/terra_surge.png": require("../assets/overwatch/heroes/orisa/terra_surge.png"),
	"pharah/profile_pic.png": require("../assets/overwatch/heroes/pharah/profile_pic.png"),
	"pharah/rocket_launcher.png": require("../assets/overwatch/heroes/pharah/rocket_launcher.png"),
	"pharah/jump_jet.png": require("../assets/overwatch/heroes/pharah/jump_jet.png"),
	"pharah/concussive_blast.png": require("../assets/overwatch/heroes/pharah/concussive_blast.png"),
	"pharah/barrage.png": require("../assets/overwatch/heroes/pharah/barrage.png"),
	"pharah/hover_jets.png": require("../assets/overwatch/heroes/pharah/hover_jets.png"),
	"reaper/profile_pic.png": require("../assets/overwatch/heroes/reaper/profile_pic.png"),
	"reaper/hellfire_shotguns.png": require("../assets/overwatch/heroes/reaper/hellfire_shotguns.png"),
	"reaper/wraith_form.png": require("../assets/overwatch/heroes/reaper/wraith_form.png"),
	"reaper/shadow_step.png": require("../assets/overwatch/heroes/reaper/shadow_step.png"),
	"reaper/death_blossom.png": require("../assets/overwatch/heroes/reaper/death_blossom.png"),
	"reaper/the_reaping.png": require("../assets/overwatch/heroes/reaper/the_reaping.png"),
	"reinhardt/profile_pic.png": require("../assets/overwatch/heroes/reinhardt/profile_pic.png"),
	"reinhardt/rocket_hammer.png": require("../assets/overwatch/heroes/reinhardt/rocket_hammer.png"),
	"reinhardt/barrier_field.png": require("../assets/overwatch/heroes/reinhardt/barrier_field.png"),
	"reinhardt/charge.png": require("../assets/overwatch/heroes/reinhardt/charge.png"),
	"reinhardt/fire_strike.png": require("../assets/overwatch/heroes/reinhardt/fire_strike.png"),
	"reinhardt/earthshatter.png": require("../assets/overwatch/heroes/reinhardt/earthshatter.png"),
	"roadhog/profile_pic.png": require("../assets/overwatch/heroes/roadhog/profile_pic.png"),
	"roadhog/scrap_gun.png": require("../assets/overwatch/heroes/roadhog/scrap_gun.png"),
	"roadhog/chain_hook.png": require("../assets/overwatch/heroes/roadhog/chain_hook.png"),
	"roadhog/take_a_breather.png": require("../assets/overwatch/heroes/roadhog/take_a_breather.png"),
	"roadhog/whole_hog.png": require("../assets/overwatch/heroes/roadhog/whole_hog.png"),
	"soldier__76/profile_pic.png": require("../assets/overwatch/heroes/soldier__76/profile_pic.png"),
	"soldier__76/heavy_pulse_rifle.png": require("../assets/overwatch/heroes/soldier__76/heavy_pulse_rifle.png"),
	"soldier__76/helix_rockets.png": require("../assets/overwatch/heroes/soldier__76/helix_rockets.png"),
	"soldier__76/sprint.png": require("../assets/overwatch/heroes/soldier__76/sprint.png"),
	"soldier__76/biotic_field.png": require("../assets/overwatch/heroes/soldier__76/biotic_field.png"),
	"soldier__76/tactical_visor.png": require("../assets/overwatch/heroes/soldier__76/tactical_visor.png"),
	"sombra/profile_pic.png": require("../assets/overwatch/heroes/sombra/profile_pic.png"),
	"sombra/machine_pistol.png": require("../assets/overwatch/heroes/sombra/machine_pistol.png"),
	"sombra/hack.png": require("../assets/overwatch/heroes/sombra/hack.png"),
	"sombra/stealth.png": require("../assets/overwatch/heroes/sombra/stealth.png"),
	"sombra/translocator.png": require("../assets/overwatch/heroes/sombra/translocator.png"),
	"sombra/emp.png": require("../assets/overwatch/heroes/sombra/emp.png"),
	"sombra/opportunist.png": require("../assets/overwatch/heroes/sombra/opportunist.png"),
	"symmetra/profile_pic.png": require("../assets/overwatch/heroes/symmetra/profile_pic.png"),
	"symmetra/photon_projector.png": require("../assets/overwatch/heroes/symmetra/photon_projector.png"),
	"symmetra/sentry_turret.png": require("../assets/overwatch/heroes/symmetra/sentry_turret.png"),
	"symmetra/teleporter.png": require("../assets/overwatch/heroes/symmetra/teleporter.png"),
	"symmetra/photon_barrier.png": require("../assets/overwatch/heroes/symmetra/photon_barrier.png"),
	"torbj_rn/profile_pic.png": require("../assets/overwatch/heroes/torbj_rn/profile_pic.png"),
	"torbj_rn/rivet_gun.png": require("../assets/overwatch/heroes/torbj_rn/rivet_gun.png"),
	"torbj_rn/deploy_turret.png": require("../assets/overwatch/heroes/torbj_rn/deploy_turret.png"),
	"torbj_rn/overload.png": require("../assets/overwatch/heroes/torbj_rn/overload.png"),
	"torbj_rn/forge_hammer.png": require("../assets/overwatch/heroes/torbj_rn/forge_hammer.png"),
	"torbj_rn/molten_core.png": require("../assets/overwatch/heroes/torbj_rn/molten_core.png"),
	"tracer/profile_pic.png": require("../assets/overwatch/heroes/tracer/profile_pic.png"),
	"tracer/pulse_pistols.png": require("../assets/overwatch/heroes/tracer/pulse_pistols.png"),
	"tracer/blink.png": require("../assets/overwatch/heroes/tracer/blink.png"),
	"tracer/recall.png": require("../assets/overwatch/heroes/tracer/recall.png"),
	"tracer/pulse_bomb.png": require("../assets/overwatch/heroes/tracer/pulse_bomb.png"),
	"widowmaker/profile_pic.png": require("../assets/overwatch/heroes/widowmaker/profile_pic.png"),
	"widowmaker/widow_s_kiss.png": require("../assets/overwatch/heroes/widowmaker/widow_s_kiss.png"),
	"widowmaker/grappling_hook.png": require("../assets/overwatch/heroes/widowmaker/grappling_hook.png"),
	"widowmaker/venom_mine.png": require("../assets/overwatch/heroes/widowmaker/venom_mine.png"),
	"widowmaker/infra_sight.png": require("../assets/overwatch/heroes/widowmaker/infra_sight.png"),
	"winston/profile_pic.png": require("../assets/overwatch/heroes/winston/profile_pic.png"),
	"winston/tesla_cannon.png": require("../assets/overwatch/heroes/winston/tesla_cannon.png"),
	"winston/barrier_projector.png": require("../assets/overwatch/heroes/winston/barrier_projector.png"),
	"winston/jump_pack.png": require("../assets/overwatch/heroes/winston/jump_pack.png"),
	"winston/primal_rage.png": require("../assets/overwatch/heroes/winston/primal_rage.png"),
	"wrecking_ball/profile_pic.png": require("../assets/overwatch/heroes/wrecking_ball/profile_pic.png"),
	"wrecking_ball/quad_cannons.png": require("../assets/overwatch/heroes/wrecking_ball/quad_cannons.png"),
	"wrecking_ball/grappling_claw.png": require("../assets/overwatch/heroes/wrecking_ball/grappling_claw.png"),
	"wrecking_ball/roll.png": require("../assets/overwatch/heroes/wrecking_ball/roll.png"),
	"wrecking_ball/adaptive_shield.png": require("../assets/overwatch/heroes/wrecking_ball/adaptive_shield.png"),
	"wrecking_ball/piledriver.png": require("../assets/overwatch/heroes/wrecking_ball/piledriver.png"),
	"wrecking_ball/minefield.png": require("../assets/overwatch/heroes/wrecking_ball/minefield.png"),
	"zarya/profile_pic.png": require("../assets/overwatch/heroes/zarya/profile_pic.png"),
	"zarya/particle_cannon.png": require("../assets/overwatch/heroes/zarya/particle_cannon.png"),
	"zarya/particle_barrier.png": require("../assets/overwatch/heroes/zarya/particle_barrier.png"),
	"zarya/projected_barrier.png": require("../assets/overwatch/heroes/zarya/projected_barrier.png"),
	"zarya/graviton_surge.png": require("../assets/overwatch/heroes/zarya/graviton_surge.png"),
	"zarya/energy.png": require("../assets/overwatch/heroes/zarya/energy.png"),
	"zenyatta/profile_pic.png": require("../assets/overwatch/heroes/zenyatta/profile_pic.png"),
	"zenyatta/orb_of_destruction.png": require("../assets/overwatch/heroes/zenyatta/orb_of_destruction.png"),
	"zenyatta/orb_of_harmony.png": require("../assets/overwatch/heroes/zenyatta/orb_of_harmony.png"),
	"zenyatta/orb_of_discord.png": require("../assets/overwatch/heroes/zenyatta/orb_of_discord.png"),
	"zenyatta/transcendence.png": require("../assets/overwatch/heroes/zenyatta/transcendence.png"),
	"zenyatta/snap_kick.png": require("../assets/overwatch/heroes/zenyatta/snap_kick.png"),
};

export const overwatchMap = {
	"escort/circuit_royal.jpg": require("../assets/overwatch/maps/escort/circuit_royal.jpg"),
	"escort/dorado.jpg": require("../assets/overwatch/maps/escort/dorado.jpg"),
	"escort/havana.jpg": require("../assets/overwatch/maps/escort/havana.jpg"),
	"escort/junkertown.jpg": require("../assets/overwatch/maps/escort/junkertown.jpg"),
	"escort/rialto.jpg": require("../assets/overwatch/maps/escort/rialto.jpg"),
	"escort/route_66.jpg": require("../assets/overwatch/maps/escort/route_66.jpg"),
	"escort/watchpoint__gibraltar.jpg": require("../assets/overwatch/maps/escort/watchpoint__gibraltar.jpg"),
	"hybrid/blizzard_world.jpg": require("../assets/overwatch/maps/hybrid/blizzard_world.jpg"),
	"hybrid/eichenwalde.jpg": require("../assets/overwatch/maps/hybrid/eichenwalde.jpg"),
	"hybrid/hollywood.jpg": require("../assets/overwatch/maps/hybrid/hollywood.jpg"),
	"hybrid/king_s_row.jpg": require("../assets/overwatch/maps/hybrid/king_s_row.jpg"),
	"hybrid/midtown.jpg": require("../assets/overwatch/maps/hybrid/midtown.jpg"),
	"hybrid/numbani.jpg": require("../assets/overwatch/maps/hybrid/numbani.jpg"),
	"hybrid/para_so.jpg": require("../assets/overwatch/maps/hybrid/para_so.jpg"),
	"control/busan.jpg": require("../assets/overwatch/maps/control/busan.jpg"),
	"control/ilios.jpg": require("../assets/overwatch/maps/control/ilios.jpg"),
	"control/lijiang_tower.jpg": require("../assets/overwatch/maps/control/lijiang_tower.jpg"),
	"control/nepal.jpg": require("../assets/overwatch/maps/control/nepal.jpg"),
	"control/oasis.jpg": require("../assets/overwatch/maps/control/oasis.jpg"),
	"push/colosseo.jpg": require("../assets/overwatch/maps/push/colosseo.jpg"),
	"push/esperan_a.jpg": require("../assets/overwatch/maps/push/esperan_a.jpg"),
	"push/new_queen_street.jpg": require("../assets/overwatch/maps/push/new_queen_street.jpg"),
	"assault/hanamura.jpg": require("../assets/overwatch/maps/assault/hanamura.jpg"),
	"assault/horizon_lunar_colony.jpg": require("../assets/overwatch/maps/assault/horizon_lunar_colony.jpg"),
	"assault/paris.jpg": require("../assets/overwatch/maps/assault/paris.jpg"),
	"assault/temple_of_anubis.jpg": require("../assets/overwatch/maps/assault/temple_of_anubis.jpg"),
	"assault/volskaya_industries.jpg": require("../assets/overwatch/maps/assault/volskaya_industries.jpg"),
	"elimination/black_forest.jpg": require("../assets/overwatch/maps/elimination/black_forest.jpg"),
	"elimination/castillo.jpg": require("../assets/overwatch/maps/elimination/castillo.jpg"),
	"elimination/ecopoint__antarctica.png": require("../assets/overwatch/maps/elimination/ecopoint__antarctica.png"),
	"elimination/necropolis.jpg": require("../assets/overwatch/maps/elimination/necropolis.jpg"),
	"deathmatch/ch_teau_guillard.jpg": require("../assets/overwatch/maps/deathmatch/ch_teau_guillard.jpg"),
	"deathmatch/kanezaka.jpg": require("../assets/overwatch/maps/deathmatch/kanezaka.jpg"),
	"deathmatch/malevento.jpg": require("../assets/overwatch/maps/deathmatch/malevento.jpg"),
	"deathmatch/petra.jpg": require("../assets/overwatch/maps/deathmatch/petra.jpg"),
	"capture_the_flag/ayutthaya.png": require("../assets/overwatch/maps/capture_the_flag/ayutthaya.png"),
};

export const roleMap = {
	damage: require(`../assets/overwatch/roles/damage_icon.png`),
	support: require(`../assets/overwatch/roles/support_icon.png`),
	tank: require(`../assets/overwatch/roles/tank_icon.png`),
};

export const weaponMap = {
	"Primary Weapon": "Primary",
	"Secondary Weapon": "Secondary",
	"Weapon Two": "Weapon Two",
	Ability: "Ability",
	Ultimate: "Ultimate",
	Passive: "Passive",
};

export const colorMap = (length, mode) => {
	const [colourArray, setColourArray] = useState([]);

	useEffect(() => {
		setColourArray(
			randomColor({
				count: length ?? 10,
				luminosity: mode ?? "light",
			})
		);
	}, []);

	return colourArray;
};

const width = Dimensions.get("window").width ?? 0;
export const dimensionsMap = {
	sm: width <= 640,
	md: width > 640 && width <= 768,
	lg: width > 768,
};
